Repository AY2324S2-CS2113-T11-4/tp, pull requests merged in 2024-03, with the labels that each got.

#39 branch-fix-tag-game
  src/main/java/command/ExerciseCommand.java
  src/main/java/exception/InvalidMarkException.java
  src/main/java/exception/InvalidMoveException.java
  src/main/java/minigame/TicTacToe.java
Labels: priority.Medium

#73 Branch save playerprofile
  src/main/java/file/Loader.java
  src/main/java/file/Saver.java
  src/main/java/gamelogic/EconoCraftLogic.java
  src/main/java/player/PlayerProfile.java
Labels: priority.High

#76 Branch company system
  src/main/java/command/AdjustSalaryCommand.java
  src/main/java/command/Command.java
  src/main/java/command/CommandFactory.java
  src/main/java/command/FireEmployeeCommand.java
  src/main/java/command/HireEmployeeCommand.java
  src/main/java/command/UpgradeCommand.java
  src/main/java/company/Company.java
  src/main/java/exception/GameException.java
  src/main/java/exception/LockedFeatureException.java
  src/main/java/exception/MoneyNotEnoughException.java
  src/main/java/file/Loader.java
  src/main/java/file/Saver.java
  src/main/java/gamelogic/EconoCraftLogic.java
  src/main/java/player/Asset.java
  src/main/java/player/Health.java
  src/main/java/player/PlayerProfile.java
  src/main/java/ui/CommandType.java
  src/main/java/ui/Parser.java
  src/main/java/ui/ResponseManager.java
  src/test/java/player/AssetTest.java
Labels: type.Story, priority.Medium

#79 add randomness to typing game
  src/main/java/gamelogic/EconoCraftLogic.java
  src/main/java/minigame/TypingGame.java
Labels: priority.Medium
