Repository AY2324S2-CS2113-T11-4/tp, pull requests merged in 2024-04, with the labels that each got.

#81 Branch stock
  src/main/java/command/CommandFactory.java
  src/main/java/command/SellStockCommand.java
  src/main/java/command/StockCommand.java
  src/main/java/minigame/stockgame/Main.java
  src/main/java/minigame/stockgame/Stock.java
  src/main/java/minigame/stockgame/StockActivate.java
  src/main/java/minigame/stockgame/StockEight.java
  src/main/java/minigame/stockgame/StockFive.java
  src/main/java/minigame/stockgame/StockFour.java
  src/main/java/minigame/stockgame/StockNine.java
  src/main/java/minigame/stockgame/StockOne.java
  src/main/java/minigame/stockgame/StockSeven.java
  src/main/java/minigame/stockgame/StockSix.java
  src/main/java/minigame/stockgame/StockStorage.java
  src/main/java/minigame/stockgame/StockTen.java
  src/main/java/minigame/stockgame/StockThree.java
  src/main/java/minigame/stockgame/StockTwo.java
  src/main/java/player/Asset.java
  src/main/java/ui/CommandType.java
  src/main/java/ui/ResponseManager.java
Labels: priority.High

#83 Update user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/command/RestCommand.java
  src/main/java/minigame/stockgame/StockEight.java
Labels: priority.Medium

#85 Fix storage issue
  .gitignore
  src/main/java/file/Loader.java
  src/main/java/file/Saver.java
Labels: priority.High

#87 Add DG for storage
  docs/DeveloperGuide.md
  docs/UML diagram/Load.png
  docs/UML diagram/Save.png
Labels: priority.Medium

#88 Fix storage folder issue
  src/main/java/file/Saver.java
Labels: priority.High

#91 Add user guide for storage
  docs/UserGuide.md
  src/main/java/file/Saver.java
Labels: priority.Medium

#92 Wrap up UG2.0
  docs/UserGuide.md
  src/main/java/randomevent/DecisionEvent.java
Labels: type.Chore, priority.Medium

#146 Fix exercise input crash bug
  src/main/java/minigame/TicTacToe.java
Labels: priority.Medium

#147 Fix french display in typing game
  src/main/java/minigame/TypingGame.java
Labels: priority.Low

#150 Update dg file
  docs/DeveloperGuide.md
  docs/UML diagram/Load.png
  docs/UML diagram/Save.png
Labels: priority.Medium

#157 Add Hangman Game to exercise
  src/main/java/command/ExerciseCommand.java
  src/main/java/minigame/Hangman.java
Labels: priority.High

#161 Save stock record
  build.gradle
  src/main/java/file/Decoder.java
  src/main/java/file/Loader.java
  src/main/java/file/Saver.java
  src/main/java/file/Serializer.java
  src/main/java/minigame/Hangman.java
  src/main/java/minigame/bondgame/Bond.java
  src/main/java/minigame/bondgame/CorporateGrowthBond.java
  src/main/java/minigame/cryptocurrency/CryptoCurrency.java
  src/main/java/minigame/stockgame/Stock.java
  src/main/java/minigame/stockgame/StockEight.java
  src/main/java/minigame/stockgame/StockFive.java
  src/main/java/minigame/stockgame/StockFour.java
  src/main/java/minigame/stockgame/StockNine.java
  src/main/java/minigame/stockgame/StockOne.java
  src/main/java/minigame/stockgame/StockSeven.java
  src/main/java/minigame/stockgame/StockSix.java
  src/main/java/minigame/stockgame/StockTen.java
  src/main/java/minigame/stockgame/StockThree.java
  src/main/java/minigame/stockgame/StockTwo.java
  src/main/java/player/Asset.java
  src/main/java/player/PlayerProfile.java
Labels: priority.High

#167 Add PPP draft for stargazerx0
  docs/team/StargazerX0.md
Labels: priority.Medium

#178 Update-DG-new-File
  docs/UML diagram/Load.png
  docs/UML diagram/Save.png
  src/main/java/file/Loader.java
Labels: priority.Medium

#179 Add JavaDoc for File package
  src/main/java/file/Decoder.java
  src/main/java/file/Loader.java
  src/main/java/file/Saver.java
  src/main/java/file/Serializer.java
Labels: priority.Medium

#180 Add JavaDoc for Exercise Game and Command
  src/main/java/command/ExerciseCommand.java
  src/main/java/minigame/Hangman.java
  src/main/java/minigame/TicTacToe.java
Labels: priority.Medium

#181 Fix DG for file package
  docs/UML diagram/Load.png
  docs/UML diagram/Save.png
Labels: priority.Medium

#183 Unit test exercise
  src/main/java/command/ExerciseCommand.java
  src/main/java/minigame/Hangman.java
  src/main/java/minigame/TicTacToe.java
  src/test/java/command/ExerciseCommandTest.java
  src/test/java/minigame/HangmanTest.java
  src/test/java/minigame/TicTacToeTest.java
Labels: priority.High

#185 Add Test Unit for file package
  src/main/java/file/Loader.java
  src/main/java/file/Saver.java
  src/test/java/file/DecoderTest.java
  src/test/java/file/LoaderTest.java
  src/test/java/file/SaverTest.java
  src/test/java/file/SerializerTest.java
Labels: priority.High

#186 Update UG for game
  docs/DeveloperGuide.md
  docs/UML diagram/Load.png
  docs/UserGuide.md
Labels: priority.Medium

#192 Add assertion for exercise game
  src/main/java/minigame/Hangman.java
  src/main/java/minigame/TicTacToe.java
Labels: priority.Medium

#193 Improve JavaDoc ExerciseGame
  src/main/java/minigame/Hangman.java
  src/main/java/minigame/TicTacToe.java
Labels: priority.Medium

#196 Update PPP for StargazerX0
  docs/team/stargazerx0.md
Labels: priority.High

#199 Update DG Implementation
  docs/DeveloperGuide.md
Labels: priority.Medium
